apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-proxy
  labels:
    app: ingress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-proxy
  template:
    metadata:
      labels:
        app: ingress-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      tolerations:
        - key: dedicated
          operator: Equal
          value: ingress
          effect: NoSchedule
      containers:
        - name: ingress-proxy
          image: 'nginx'
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          # volumeMounts:
          #   - name: web-certs
          #     mountPath: /cert
          #     readOnly: true
      # volumes:
      #   - name: web-certs
      #     secret:
      #       secretName: web-certs
