apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-proxy
  labels:
    app: ingress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-proxy
  template:
    metadata:
      labels:
        app: ingress-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      tolerations:
        - key: dedicated
          operator: Equal
          value: ingress
          effect: NoSchedule
      containers:
        - name: ingress-proxy
          image: 'gcr.io/homin-dev/ingress:latest'
          args: ["-c", "/conf/links.yaml"]
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
          volumeMounts:
            - name: ingress-links
              mountPath: /conf  
            - name: cert-letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: ingress-links
          configMap:
            name: links
        - name: cert-letsencrypt
          hostPath:
            path: /etc/letsencrypt
            type: DirectoryOrCreate
